# Generated by Django 4.2.7 on 2026-06-13 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('condition_type', models.CharField(choices=[('contains', 'Contains text'), ('level_equals', 'Level equals'), ('error_rate', 'Error rate exceeds'), ('frequency', 'Frequency exceeds')], max_length=20)),
                ('service_filter', models.CharField(blank=True, max_length=100)),
                ('level_filter', models.CharField(blank=True, max_length=20)),
                ('text_pattern', models.TextField(blank=True)),
                ('threshold_value', models.IntegerField(default=5)),
                ('threshold_window_minutes', models.IntegerField(default=5)),
                ('enabled', models.BooleanField(default=True)),
                ('email_recipients', models.TextField(blank=True, help_text='Comma-separated emails')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LogRetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('service_pattern', models.CharField(max_length=100)),
                ('retention_days', models.IntegerField(default=30)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_cleanup', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('source_type', models.CharField(choices=[('file', 'File Upload'), ('syslog', 'Syslog'), ('api', 'API')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], db_index=True, max_length=20)),
                ('service', models.CharField(db_index=True, max_length=100)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_anomaly', models.BooleanField(db_index=True, default=False)),
                ('anomaly_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='logs.logsource')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'level'], name='logs_log_timesta_c4352a_idx'), models.Index(fields=['service', 'timestamp'], name='logs_log_service_7fca95_idx'), models.Index(fields=['is_anomaly', 'timestamp'], name='logs_log_is_anom_76c8fe_idx')],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('triggered', 'Triggered'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='triggered', max_length=20)),
                ('log_count', models.IntegerField()),
                ('message', models.TextField()),
                ('details', models.JSONField(default=dict)),
                ('triggered_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='logs.alertrule')),
            ],
            options={
                'ordering': ['-triggered_at'],
                'indexes': [models.Index(fields=['status', 'triggered_at'], name='logs_alert_status_897f07_idx'), models.Index(fields=['rule', 'triggered_at'], name='logs_alert_rule_id_cff440_idx')],
            },
        ),
    ]
